medoplay10/sam-mart-api

- src/modules/authentication/dto/requests/driver-register.dto.ts
> H-sprint-1

- src/infrastructure/entities/driver/driver.entity.ts
- src/modules/driver/driver.service.ts
- src/modules/driver/requests/update-driver-location.request.ts
> Fix Address

- package-lock.json
- src/core/setups/index.ts
- src/core/setups/schedule.setup.ts
- src/core/setups/swagger.setup.ts
- src/infrastructure/context/database.context.ts
- src/infrastructure/entities/banar/banar.entity.ts
- src/infrastructure/entities/category/most-hit-subcategory.entity.ts
- src/infrastructure/entities/category/subcategory.entity.ts
- src/modules/assembly.module.ts
- src/modules/banar/banar.controller.ts
- src/modules/banar/banar.module.ts
- src/modules/banar/banar.service.ts
- src/modules/banar/dto/request/create-banar.request.ts
- src/modules/banar/dto/request/update-banner.request.ts
- src/modules/banar/dto/response/banner.response.ts
- src/modules/category/category.controller.ts
- src/modules/category/category.service.ts
- src/modules/product/product.service.ts
This pull request introduces several enhancements and new functionalities to the codebase, addressing various aspects:
- Added/Modified Entities: `MostHitSubcategory`, `Banar`
- Updated Controllers: `BanarController`
- Enhanced Services: `BanarService`, `CategoryService`, `ProductService`
- Added/Updated Request and Response Objects
The purpose of these changes is to introduce and enhance functionalities related to banner management, subcategory hit counts, API handling, and database maintenance, improving system modularity, scalability, and reliability. 
---
<p align="center"> @ahmedeid6842 </p>
<p align="center">
</p>
> Feature Enhancements: Banner Management, Subcategory Hit Counts.

- src/infrastructure/entities/user/user.entity.ts
- src/modules/authentication/dto/requests/register.dto.ts
- src/modules/authentication/transactions/register-user.transaction.ts
- src/modules/user/dto/requests/update-profile.request.ts
- src/modules/user/dto/responses/profile.response.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.module.ts
- src/modules/user/user.service.ts
This pull request is a comprehensive refinement and enhancement of the profile management functionality, aiming to empower users with more control over their profiles. Additionally, it introduces a set of updates to enrich user data handling and improve the overall user experience within the application.
1. **UserController Improvements:**
2. **UserService Enhancements:**
4. **RegisterRequest:**
5. **UpdateProfileRequest:**
6. **UserInfoResponse:**
7. **UserInfoResponse Enhancement:**
- Empowers users with enhanced profile management tools, providing a smoother and more intuitive experience.
- Offers greater flexibility in updating and managing profile details, fostering a sense of control and personalization for users.
- Elevates code quality, readability, and scalability for future …
> Feature: Profile Management Refinement and User Data Augmentation

- src/core/setups/index.ts
- src/core/setups/serve-static.setup.ts
Solve default avatar not found
> Enable ServeStaticSetup in index.ts

- src/core/base/router.ts
- src/infrastructure/data/enums/driver-status.enum.ts
- src/infrastructure/entities/driver/driver.entity.ts
- src/modules/authentication/authentication.controller.ts
- src/modules/authentication/authentication.service.ts
- src/modules/authentication/dto/requests/update-driver-status.request.ts
- src/modules/authentication/guards/roles.guard.ts
- src/modules/authentication/transactions/register-driver.transaction.ts
- src/modules/authentication/transactions/verify-otp.transaction.ts
- src/modules/warehouse/warehouse.service.ts
This pull request introduces a new feature for updating the status of a driver within the authentication module. The update is facilitated through a new API endpoint, `update-driver-status`, which is secured using JWT authentication and role-based authorization.
---
1. **AuthenticationController:**
- Added a new API endpoint `@Post(Router.Auth.UpdateDriverStatus)` to handle the driver status update.
- Created the `updateDriverStatus` method to process the status update request and return the updated driver information.
2. **AuthenticationService:**
- Implemented the `updateDriverStatus` method to update the driver's status and status reason.
- Checked for the existence of the driver based on the provided `driver_id`.
- If the driver is not found, a `BadRequestException` is thrown.
- …
> Feature: Implement Driver Status Update Functionality :motor_scooter:

- src/modules/section/dto/requests/create-sections-excel.request.ts
- src/modules/section/section.service.ts
**Pull Request Description:**
This pull request refactors the data structure used within `flattenedData.push()` to simplify and streamline the object properties. 
**Changes Made:**
- Renamed `section_name_ar` to `name_ar`.
- Renamed `section_name_en` to `name_en`.
- Renamed `section_logo` to `logo`.
- Removed `category_name_ar`, `category_name_en`, `category_logo`.
- Updated the property assignments to directly use properties from the `section` object.
**Impact:**
- Aligns the exported sheet format with the required import format, ensuring seamless data transfer between systems.
> Refactor section service to use flattened data structure :stars: 

- src/modules/warehouse/warehouse.controller.ts
- src/modules/warehouse/warehouse.service.ts
This pull request introduces functionality to attach a driver to a warehouse based on the provided IDs. It includes additions to the `WarehouseController` to handle the attachment endpoint and modifications to the `WarehouseService` to implement the attachment logic.
- **New Endpoint:** `POST /attach-driver/:warehouse_id/:driver_id` is added to the `WarehouseController` with appropriate authorization using `@Roles(Role.ADMIN)`.
- **Service Method:** `attachDriverToWarehouse` is implemented in the `WarehouseService` to handle the attachment logic.
- **Validation:** Checks for the existence of warehouse and driver, ensuring that they are valid entities before proceeding with attachment.
- **Preventing Duplicate Attachment:** Prevents attaching a driver to a warehouse if they are already …
> Feature: Introduce Endpoint and Service Method for Attaching Drivers to Warehouses :heavy_plus_sign: 🚛

- json/support-ticket-subjects.json
- src/infrastructure/context/database.context.ts
- src/infrastructure/entities/support-ticket/support-ticket.entity.ts
- src/infrastructure/entities/support-ticket/suppot-ticket-subject.entity.ts
- src/infrastructure/presistance/seeders/initial.seeder.ts
- src/infrastructure/presistance/seeders/suppot-ticket-subjects.seeder.ts
- src/modules/support-ticket/dto/request/create-support-subject.request.ts
- src/modules/support-ticket/dto/request/create-ticket.request.ts
- src/modules/support-ticket/dto/response/support-ticket.response.ts
- src/modules/support-ticket/dto/response/suppot-ticket-subject.response.ts
- src/modules/support-ticket/support-ticket.controller.ts
- src/modules/support-ticket/support-ticket.service.ts
This pull request introduces several enhancements to the Support Ticket module. The changes aim to improve the functionality and maintainability of the module.
1. **SupportTicketController**:
2. **SupportTicketService**:
3. **SupportTicketSubject Entity**:
4. **SupportTicketSubjectSeeder**:
5. **Support Ticket Subject JSON Data**:
6. **CreateSupportTicketSubjectRequest**:
7. **SupportTicketSubjectResponse**:
- The addition of support ticket subjects allows users to categorize their support tickets effectively.
- This enhancement enhances the overall organization and management of support tickets within the system.
- The introduction of DTOs ensures proper validation and standardization of data transferred between client and server.
```json
[
{ "title": "Account Access Issue" },
{ "title": …
```
> Enhancement: Introduce Support Ticket Subject Management :mega: 📝

- src/modules/warehouse/dto/requests/warehouse-transfer-product.request.ts
- src/modules/warehouse/warehouse.controller.ts
- src/modules/warehouse/warehouse.service.ts
This pull request introduces enhancements to the warehouse product transfer functionality, improving the clarity, efficiency, and error handling of the process. Refactor transferWarehouseProducts method to handle multiple warehouse products at the same request.
1. **Updated `transferWarehouseProducts` Method in `WarehouseService`**:
- **Old Code**:
- Implemented the transfer of a single warehouse product from one warehouse to another.
- **New Code**:
2. **Updated `transferWarehouseProducts` Route in `WarehouseController`**:
- **Old Code**:
- Defined a route for transferring a single warehouse product.
- **New Code**:
3. **Updated `WarehouseTransferProductRequest` DTO**:
- **Old Code**:
- Defined a DTO for transferring a single warehouse product, including quantity.
- **New Code**:
- The …
> Enhancements: Refactor Warehouse Product Transfer to Handle Multiple warehouse products :arrow_down: :arrow_up: :package: 

- src/infrastructure/entities/order/shipment.entity.ts
- src/infrastructure/entities/working-area/working-area.entity.ts
- src/modules/order/dto/request/cancel-shipment.request.ts
- src/modules/order/shipment.controller.ts
- src/modules/order/shipment.service.ts
This pull request introduces enhancements to the `cancelShipment` method in order to enforce more robust validation rules regarding shipment cancellation eligibility based on user roles and shipment status.
- Added validation checks to ensure that only authorized users can cancel shipments.
- Implemented logic to prevent cancellation of shipments based on their current status and user roles.
- Introduced the `currentUserRole` variable to retrieve the roles of the current user invoking the cancellation operation.
- Utilized the `shipmentStatus` variable to obtain the status of the shipment being canceled.
- Added validation conditions to verify user authorization based on their role and ownership of the shipment.
- Implemented checks to prevent cancellation of shipments in certain statuses …
> 🚚✨ Enhance shipment cancellation validation logic 🔄

- src/core/validators/upload.validator.ts
- src/modules/authentication/authentication.controller.ts
- src/modules/authentication/transactions/register-driver.transaction.ts
Reverts medoplay10/sam-mart-api#136
> Revert "try fix register"

- src/core/validators/upload.validator.ts
- src/modules/authentication/authentication.controller.ts
- src/modules/authentication/transactions/register-driver.transaction.ts
Reverts medoplay10/sam-mart-api#137
> Revert "Revert "try fix register""

- src/infrastructure/entities/order/return-order/return-order.entity.ts
- src/integration/gateways/dto/response/order-gateway.response.ts
- src/integration/gateways/dto/response/return-order.response.ts
- src/integration/gateways/interfaces/order/return-order.payload.ts
- src/integration/gateways/order.gateway.ts
- src/modules/order/order.service.ts
This pull request introduces several enhancements to the order management system, particularly focusing on handling return orders and notifying stakeholders about order status changes. The changes encompass modifications in entity structures, payload definitions, and service methods to improve the efficiency and accuracy of return order processing.
1. **Updated ReturnOrderRequest Class**
- Added new attributes (`id`, `status`, `admin_note`, `customer_note`, `order_id`) to facilitate comprehensive return order data handling.
2. **Enhanced ReturnOrderResponse Class**
- Extended `OrderStatusChangeResponse` to incorporate return order specifics.
- Added `returnOrder` property to encapsulate the details of a return order request.
3. **Refined ReturnOrderPayload Interface**
- Expanded payload …
> Enhancements for Efficient Return Order Management and Notification Handling 📦 :arrow_up_down: 

- src/integration/gateways/dto/response/order-gateway.response.ts
- src/integration/gateways/order.gateway.ts
- src/modules/order/order.service.ts
- src/modules/order/shipment.service.ts
- src/modules/order/util/make-order.transaction.ts
> Fixed Order Gateway Response :hammer: 

- src/modules/order/shipment.service.ts
> Fix Cancel Order from Driver 

- src/modules/order/shipment.controller.ts
> Add DTOs to shipment controller :hammer: :eye: 

- src/modules/order/order.service.ts
- src/modules/order/return-order.service.ts
> Fix Update Return Order Status Wasn't Working :hammer: :lady_beetle: 

- src/modules/banar/banar.controller.ts
- src/modules/banar/banar.service.ts
> Fix: Return All the banners for the admin

- src/modules/banar/banar.controller.ts
- src/modules/banar/banar.service.ts
- src/modules/banar/dto/request/update-banner.request.ts
> Feature: Add Endpoint to get banner with Id
